"""Provider registry and cross-provider sanity checks."""
from __future__ import annotations

from llm_cookie_bridge.client import _PROVIDERS

EXPECTED_PROVIDERS = [
    "gemini",
    "chatgpt",
    "claude",
    "perplexity",
    "huggingface",
    "grok",
    "phind",
    "deepseek",
    "you",
    "pi",
    "meta",
    "mistral",
    "copilot",
    "poe",
    "blackbox",
    "characterai",
    "qwen",
    "tongyi",
    "duckai",
    "zai",
    "kimi",
    "lmarena",
    "openrouter",
    "groq",
    "together",
    "githubmodels",
    "doubao",
    "yuanbao",
    "chatglm",
    "sparkdesk",
    "hailuo",
    "iask",
    "scira",
    "komo",
    "andi",
    "felo",
    "devv",
    "venice",
    "deepai",
    "aistudio",
    "notebooklm",
    "cohere",
    "lumo",
    "v0",
    "bolt",
    "lovable",
    "websim",
    "monica",
    "sider",
    "merlin",
    "popai",
    "genspark",
    "skywork",
    "sensechat",
    "baichuan",
    "wrtn",
    "coze",
    "kagi",
    "cody",
    "ai360",
    "abacus",
]


def test_all_providers_registered() -> None:
    for name in EXPECTED_PROVIDERS:
        assert name in _PROVIDERS, f"Provider '{name}' missing from registry"


def test_provider_count() -> None:
    assert len(_PROVIDERS) == len(EXPECTED_PROVIDERS)
    assert len(_PROVIDERS) > 50


def test_provider_base_urls() -> None:
    expected_urls = {
        "gemini": "https://gemini.google.com",
        "chatgpt": "https://chatgpt.com",
        "claude": "https://claude.ai",
        "perplexity": "https://www.perplexity.ai",
        "huggingface": "https://huggingface.co",
        "grok": "https://grok.com",
        "phind": "https://www.phind.com",
        "deepseek": "https://chat.deepseek.com",
        "you": "https://you.com",
        "pi": "https://pi.ai",
        "meta": "https://www.meta.ai",
        "mistral": "https://chat.mistral.ai",
        "copilot": "https://copilot.microsoft.com",
        "poe": "https://poe.com",
        "blackbox": "https://api.blackbox.ai",
        "characterai": "https://neo.character.ai",
        "qwen": "https://chat.qwen.ai",
        "tongyi": "https://www.qianwen.com",
        "duckai": "https://duckduckgo.com",
        "zai": "https://chat.z.ai",
        "kimi": "https://www.kimi.com",
        "lmarena": "https://lmarena.ai",
        "openrouter": "https://openrouter.ai",
        "groq": "https://api.groq.com",
        "together": "https://api.together.xyz",
        "githubmodels": "https://models.github.ai",
        "doubao": "https://www.doubao.com",
        "yuanbao": "https://yuanbao.tencent.com",
        "chatglm": "https://chatglm.cn",
        "sparkdesk": "https://xinghuo.xfyun.cn",
        "hailuo": "https://www.hailuo.ai",
        "iask": "https://iask.ai",
        "scira": "https://scira.ai",
        "komo": "https://komo.ai",
        "andi": "https://andisearch.com",
        "felo": "https://felo.ai",
        "devv": "https://devv.ai",
        "venice": "https://venice.ai",
        "deepai": "https://deepai.org",
        "aistudio": "https://aistudio.google.com",
        "notebooklm": "https://notebooklm.google.com",
        "cohere": "https://api.cohere.com",
        "lumo": "https://lumo.proton.me",
        "v0": "https://v0.dev",
        "bolt": "https://bolt.new",
        "lovable": "https://lovable.dev",
        "websim": "https://websim.ai",
        "monica": "https://monica.im",
        "sider": "https://sider.ai",
        "merlin": "https://www.getmerlin.in",
        "popai": "https://popai.pro",
        "genspark": "https://www.genspark.ai",
        "skywork": "https://skywork.ai",
        "sensechat": "https://chat.sensetime.com",
        "baichuan": "https://www.baichuan-ai.com",
        "wrtn": "https://wrtn.ai",
        "coze": "https://www.coze.com",
        "kagi": "https://kagi.com",
        "cody": "https://sourcegraph.com",
        "ai360": "https://bot.n.cn",
        "abacus": "https://apps.abacus.ai",
    }
    for name, expected_url in expected_urls.items():
        cls = _PROVIDERS[name]
        assert cls.default_base_url == expected_url, (
            f"{name}: expected {expected_url!r}, got {cls.default_base_url!r}"
        )
