from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Literal, Self

import httpx

from .providers import (
    AbacusProvider,
    AI360Provider,
    AIStudioProvider,
    AndiProvider,
    BaichuanProvider,
    BlackboxProvider,
    BoltProvider,
    CharacterAIProvider,
    ChatGLMProvider,
    ChatGPTProvider,
    ClaudeProvider,
    CodyProvider,
    CohereProvider,
    CopilotProvider,
    CozeProvider,
    DeepAIProvider,
    DeepSeekProvider,
    DevvProvider,
    DoubaoProvider,
    DuckAIProvider,
    FeloProvider,
    GeminiProvider,
    GensparkProvider,
    GitHubModelsProvider,
    GrokProvider,
    GroqProvider,
    HailuoProvider,
    HuggingFaceProvider,
    IAskProvider,
    KagiProvider,
    KimiProvider,
    KomoProvider,
    LMArenaProvider,
    LovableProvider,
    LumoProvider,
    MerlinProvider,
    MetaAIProvider,
    MistralProvider,
    MonicaProvider,
    NotebookLMProvider,
    OpenRouterProvider,
    PerplexityProvider,
    PhindProvider,
    PiProvider,
    PoeProvider,
    PopAIProvider,
    QwenProvider,
    SciraProvider,
    SenseChatProvider,
    SiderProvider,
    SkyworkProvider,
    SparkDeskProvider,
    TogetherProvider,
    TongyiProvider,
    V0Provider,
    VeniceProvider,
    WebSimProvider,
    WrtnProvider,
    YouProvider,
    YuanbaoProvider,
    ZaiProvider,
)
from .providers.base import BaseProvider
from .types import ChatChunk, ChatResponse

ProviderName = Literal[
    "gemini",
    "chatgpt",
    "claude",
    "perplexity",
    "huggingface",
    "grok",
    "phind",
    "deepseek",
    "you",
    "pi",
    "meta",
    "mistral",
    "copilot",
    "poe",
    "blackbox",
    "characterai",
    "qwen",
    "tongyi",
    "duckai",
    "zai",
    "kimi",
    "lmarena",
    "openrouter",
    "groq",
    "together",
    "githubmodels",
    "doubao",
    "yuanbao",
    "chatglm",
    "sparkdesk",
    "hailuo",
    "iask",
    "scira",
    "komo",
    "andi",
    "felo",
    "devv",
    "venice",
    "deepai",
    "aistudio",
    "notebooklm",
    "cohere",
    "lumo",
    "v0",
    "bolt",
    "lovable",
    "websim",
    "monica",
    "sider",
    "merlin",
    "popai",
    "genspark",
    "skywork",
    "sensechat",
    "baichuan",
    "wrtn",
    "coze",
    "kagi",
    "cody",
    "ai360",
    "abacus",
]

_PROVIDERS: dict[str, type[BaseProvider]] = {
    "gemini": GeminiProvider,
    "chatgpt": ChatGPTProvider,
    "claude": ClaudeProvider,
    "perplexity": PerplexityProvider,
    "huggingface": HuggingFaceProvider,
    "grok": GrokProvider,
    "phind": PhindProvider,
    "deepseek": DeepSeekProvider,
    "you": YouProvider,
    "pi": PiProvider,
    "meta": MetaAIProvider,
    "mistral": MistralProvider,
    "copilot": CopilotProvider,
    "poe": PoeProvider,
    "blackbox": BlackboxProvider,
    "characterai": CharacterAIProvider,
    "qwen": QwenProvider,
    "tongyi": TongyiProvider,
    "duckai": DuckAIProvider,
    "zai": ZaiProvider,
    "kimi": KimiProvider,
    "lmarena": LMArenaProvider,
    "openrouter": OpenRouterProvider,
    "groq": GroqProvider,
    "together": TogetherProvider,
    "githubmodels": GitHubModelsProvider,
    "doubao": DoubaoProvider,
    "yuanbao": YuanbaoProvider,
    "chatglm": ChatGLMProvider,
    "sparkdesk": SparkDeskProvider,
    "hailuo": HailuoProvider,
    "iask": IAskProvider,
    "scira": SciraProvider,
    "komo": KomoProvider,
    "andi": AndiProvider,
    "felo": FeloProvider,
    "devv": DevvProvider,
    "venice": VeniceProvider,
    "deepai": DeepAIProvider,
    "aistudio": AIStudioProvider,
    "notebooklm": NotebookLMProvider,
    "cohere": CohereProvider,
    "lumo": LumoProvider,
    "v0": V0Provider,
    "bolt": BoltProvider,
    "lovable": LovableProvider,
    "websim": WebSimProvider,
    "monica": MonicaProvider,
    "sider": SiderProvider,
    "merlin": MerlinProvider,
    "popai": PopAIProvider,
    "genspark": GensparkProvider,
    "skywork": SkyworkProvider,
    "sensechat": SenseChatProvider,
    "baichuan": BaichuanProvider,
    "wrtn": WrtnProvider,
    "coze": CozeProvider,
    "kagi": KagiProvider,
    "cody": CodyProvider,
    "ai360": AI360Provider,
    "abacus": AbacusProvider,
}


class LLMCookieBridge:
    def __init__(self, provider: BaseProvider) -> None:
        self.provider = provider

    @classmethod
    def create(
        cls,
        provider: ProviderName,
        *,
        cookies: dict[str, str] | None = None,
        cookie_header: str | None = None,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
        transport: httpx.AsyncBaseTransport | None = None,
        refresh_callback: Any = None,
        allow_custom_base_url: bool = False,
        follow_redirects: bool = False,
        **provider_kwargs: Any,
    ) -> LLMCookieBridge:
        provider_cls = _PROVIDERS[provider]
        instance = provider_cls(
            cookies=cookies,
            cookie_header=cookie_header,
            headers=headers,
            timeout=timeout,
            transport=transport,
            refresh_callback=refresh_callback,
            allow_custom_base_url=allow_custom_base_url,
            follow_redirects=follow_redirects,
            **provider_kwargs,
        )
        return cls(instance)

    async def refresh(self, force: bool = False) -> None:
        await self.provider.refresh(force=force)

    async def chat(self, message: str, **kwargs: Any) -> ChatResponse:
        return await self.provider.chat(message, **kwargs)

    async def stream(self, message: str, **kwargs: Any) -> AsyncIterator[ChatChunk]:
        async for chunk in self.provider.stream_chat(message, **kwargs):
            yield chunk

    async def aclose(self) -> None:
        await self.provider.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.aclose()
